services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    container_name: maekok-app
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next
      - ./public:/app/public
      - .env:/app/.env
    command: yarn start
    networks:
      - nginx_networks

networks:
  nginx_networks:
    external: true
